### ISSUE TITLE
Filesystem in the Virtualbox for the manager not large enough

### ISSUE THREAD

**Issue by angel-devicente** [tcooper/warewulf-vagrant#5]
Upon 'vagrant up' I get the following error:

```
    mgr: (11/19): libselinux-devel-2.9-5.el8.x86_64.rpm  4.4 MB/s | 199 kB     00:00
    mgr: (12/19): libsepol-devel-2.9-3.el8.x86_64.rpm    2.1 MB/s |  86 kB     00:00
    mgr: (13/19): libverto-devel-0.3.0-5.el8.x86_64.rpm  457 kB/s |  17 kB     00:00
    mgr: (14/19): golang-src-1.17.7-1.module+el8.6.0+824 6.0 MB/s | 9.0 MB     00:01
    mgr: (15/19): openssl-devel-1.1.1k-6.el8_5.x86_64.rp 6.6 MB/s | 2.3 MB     00:00
    mgr: (16/19): pcre2-devel-10.32-2.el8.x86_64.rpm     7.0 MB/s | 604 kB     00:00
    mgr: (17/19): pcre2-utf16-10.32-2.el8.x86_64.rpm     4.9 MB/s | 228 kB     00:00
    mgr: (18/19): pcre2-utf32-10.32-2.el8.x86_64.rpm     4.9 MB/s | 219 kB     00:00
    mgr: (19/19): golang-bin-1.17.7-1.module+el8.6.0+824  23 MB/s |  98 MB     00:04
    mgr: --------------------------------------------------------------------------------
    mgr: Total                                            23 MB/s | 115 MB     00:04
    mgr: Running transaction check
    mgr: Transaction check succeeded.
    mgr: Running transaction test
    mgr: The downloaded packages were saved in cache until the next successful transaction.
    mgr: You can remove cached packages by executing 'dnf clean packages'.
    mgr: Error: Transaction test error:
    mgr:   installing package golang-bin-1.17.7-1.module+el8.6.0+824+8e984c20.x86_64 needs 81MB on the / filesystem
    mgr:   installing package golang-1.17.7-1.module+el8.6.0+824+8e984c20.x86_64 needs 89MB on the / filesystem
    mgr:   installing package dhcp-server-12:4.3.6-47.el8.x86_64 needs 91MB on the / filesystem
    mgr:   installing package tftp-server-5.2-24.el8.x86_64 needs 91MB on the / filesystem
    mgr: 
    mgr: Error Summary
    mgr: -------------
    mgr: Disk Requirements:
    mgr:    At least 91MB more space needed on the / filesystem.
    mgr: 
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```
